### PR TITLE
Merge updated gitignore into branch master

### PR DESCRIPTION
**Pull request by isaacaj**

### CODE REVIEW

**Comment by ritikmishra** [comment]
No! Leaving certain project files outside of the gitignore, especially those related to modules, break the left hand file browser for me.

**Comment by UltraX3** [comment]
additionally, I do not believe `.iml` files are required for formatting. It is just the `.idea/codeStyles` directory. I think it makes the most sense for this to be the only part of the `.idea/` folder that is kept.

**Comment by donovanMaas** [comment]
The IML files inside the `.idea` are required for the project specific formatter. `RobotCode2018.iml` is already added to the `.gitignore`. This commit is completely safe.

**Comment by donovanMaas** [comment]
@UltraX3 Did you not see the comment saying `Do not ignore `*.iml`, required for project formatter.`?

**Comment by donovanMaas** [comment]
@UltraX3 You had previously stated that you needed to create IML files in the `.idea/` folder for the project formatter. I do not recall you ever mentioning that you have to use `.idea/codeStyles`.

**Comment by donovanMaas** [comment]
@Mky135 Class names need to be `CamelCase`.

**Pull request merged**
